import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/sidebar/page";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
//   header,
//   footer,
// }: Readonly<{
//   children: React.ReactNode;
//   header: React.ReactNode;
//   footer: React.ReactNode;
// }>) {
//   return (

//       <html>

//           {header}

//         <body>{children}</body>
//         {footer}

//       </html>

//   );
// }

export default function Layout({
  children,
  header,
  footer,
}: {
  children: React.ReactNode;
  footer: React.ReactNode;
  header: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body>
            <Sidebar />
            {children}
        </body>
      </html>
    </>
  );
}
